name: Deploy Crackling-AWS

on:
  workflow_dispatch:

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Update build environment
        run: 'sudo apt update'

      - name: Setup Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install AWS CDK
        run: 'sudo npm install -g aws-cdk'

      - name: Install Requirements 
        run: 'pip3 install -r aws/requirements.txt'
  
      - name: Create Lambda layer with NCBI dependency
        run: 'mkdir layers/ncbi/python && py -3 -m pip install --target layers/ncbi/python -r layers/ncbi_reqs.txt'

      - name: Create Lambda layer with lib dependencies (1/2)
        run: "ldd layers/isslScoreOfftargets/isslScoreOfftargets | grep \"=> /\" | awk '{print $3}' | xargs -I '{}' cp -v '{}' layers/sharedObjects"

      - name: Create Lambda layer with lib dependencies (2/2)
        run: "ldd layers/rnaFold/rnaFold/RNAfold | grep \"=> /\" | awk '{print $3}' | xargs -I '{}' cp -v '{}' layers/sharedObjects"

      - name: CDK Synth
        run: cdk synth
    
      - name: CDK Deploy
        run: cdk deploy --verbose -c name=${{ vars.AWS_STACK_NAME }}
       
